# Generated by Django 4.0 on 2023-04-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Myapp', '0002_alter_userprofile_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
